
import { GoogleGenAI, Type } from "@google/genai";
import { Post, CategoryType } from "../types";

// Always use named parameter and direct access to process.env.API_KEY
const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

export const generatePostFromTitle = async (title: string, category: CategoryType): Promise<Partial<Post>> => {
  const model = 'gemini-3-flash-preview';
  
  const prompt = `Generate a full government job/result details for: "${title}" in category "${category}".
  The response must be in Hindi where specified and strictly follow the JSON schema.
  
  - description: 300-500 words summary in Hindi.
  - howTo: 500-1000 words guide on how to apply/check in Hindi.
  - vacancyDetails: 1000-2500 words complete details (vacancy distribution, selection process) in Hindi.
  - eligibility: Detailed eligibility criteria in Hindi.
  - importantDates: Array of objects {label, value} (e.g., Application Start).
  - fees: Array of objects {label, value} (e.g., Gen/OBC).
  - ageLimit: Age criteria as string in Hindi.
  - links: Suggested links like 'Apply Online', 'Download Notification'.
  - hindiTitle: A formal Hindi title for the post.`;

  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: {
        // Removed googleSearch tool as guidelines state response.text may not be JSON and should not be parsed when using it.
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.OBJECT,
          properties: {
            hindiTitle: { type: Type.STRING },
            description: { type: Type.STRING },
            howTo: { type: Type.STRING },
            vacancyDetails: { type: Type.STRING },
            eligibility: { type: Type.STRING },
            ageLimit: { type: Type.STRING },
            importantDates: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  label: { type: Type.STRING },
                  value: { type: Type.STRING }
                }
              }
            },
            fees: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  label: { type: Type.STRING },
                  value: { type: Type.STRING }
                }
              }
            },
            links: {
              type: Type.ARRAY,
              items: {
                type: Type.OBJECT,
                properties: {
                  label: { type: Type.STRING },
                  url: { type: Type.STRING }
                }
              }
            }
          },
          required: ["hindiTitle", "description", "howTo", "vacancyDetails", "eligibility", "importantDates", "fees", "links"]
        }
      }
    });

    // Access .text property directly (not as a function call)
    const data = JSON.parse(response.text || '{}');
    return {
      ...data,
      title,
      category,
      id: Math.random().toString(36).substr(2, 9),
      createdAt: new Date().toISOString(),
      status: 'draft',
      isAutoGenerated: true
    };
  } catch (error) {
    console.error("Gemini Generation Error:", error);
    throw error;
  }
};

export const fetchLatestJobsFromWeb = async (): Promise<Partial<Post>[]> => {
  const model = 'gemini-3-flash-preview';
  const prompt = `Identify 5-10 current government job vacancies or results trending today in India. Provide their basic info in an array of objects: {title, category}.`;
  
  try {
    const response = await ai.models.generateContent({
      model,
      contents: prompt,
      config: {
        // googleSearch removed here to ensure output is strictly JSON and can be safely parsed.
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              title: { type: Type.STRING },
              category: { type: Type.STRING, description: 'One of: Result, Admit Card, Latest Job, Answer Key, Syllabus, Admission' }
            }
          }
        }
      }
    });
    // Access .text property directly
    return JSON.parse(response.text || '[]');
  } catch (error) {
    console.error("Web Fetch Error:", error);
    return [];
  }
};
