
export type PostStatus = 'draft' | 'live';
export type CategoryType = 'Result' | 'Admit Card' | 'Latest Job' | 'Answer Key' | 'Syllabus' | 'Admission';

export interface Post {
  id: string;
  title: string;
  hindiTitle: string;
  category: CategoryType;
  description: string;
  howTo: string;
  importantDates: { label: string; value: string }[];
  fees: { label: string; value: string }[];
  ageLimit: string;
  vacancyDetails: string;
  eligibility: string;
  links: { label: string; url: string }[];
  status: PostStatus;
  createdAt: string;
  isAutoGenerated?: boolean;
}

export interface SiteSettings {
  siteName: string;
  slogan: string;
  primaryColor: string;
  secondaryColor: string;
  logoUrl: string;
  publisherId: string;
  copyProtection: boolean;
  socialLinks: { platform: string; url: string }[];
  adminPassword?: string; // New field
}

export interface StaticPage {
  id: string;
  title: string;
  content: string;
  slug: string;
}

export interface Blog {
  id: string;
  title: string;
  content: string;
  createdAt: string;
}
